parser: "@typescript-eslint/parser"

parserOptions:
  project: ./tsconfig.json

# where the code is going to be executed
env:
  node: true
  es6: true
  mocha: true

extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"

plugins:
  - "@typescript-eslint"

rules:
  comma-dangle:
    - error
    - objects: always-multiline
      arrays: always-multiline
      imports: never
      exports: never
      functions: never
  semi:
    - error

ignorePatterns:
  - scripts
  - dist
