parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    modules: true
# where the code is going to be executed
env:
  node: true

extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/recommended"
  - recommended-requiring-type-checking

rules:
  comma-dangle:
    - error
    - objects: always-multiline
      arrays: always-multiline
      imports: never
      exports: never
      functions: never
  semi:
    - error

ignorePatterns:
  - scripts
  - dist
